version: '3.8'

services:
  mcp-server-qdrant:
    build:
      context: .
    environment:
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAME=memories
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - EMBEDDING_PROVIDER=sentence-transformers
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
  
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    
volumes:
  qdrant_data: 